### PR TITLE
Update GET Messages Endpoint

### PR DESCRIPTION
**Pull request by juanarias93**
## What && Why
Update `GET /groups/:group_id/messages` endpoint so that it starts returning grouped messages by date.
Remove unused `hour` attribute from messages.

## How
- [x] Add scope to `Message` model for returning grouped messages by date.
- [x] Update controller and tests.
- [x] Update serializer to start using `created_at` instead of `hour`.
- [x] Remove unused `hour` attribute from messages.

## Links
-  [NO TICKET]

## How to Review
- [x] Review commit by commit recommended.
- [ ] Review all at once recommended.

## Output
```
== 20231104193818 RemoveHourFromMessages: migrating ===========================
-- remove_column(:messages, :hour, :datetime, {:if_exists=>true})
   -> 0.0054s
== 20231104193818 RemoveHourFromMessages: migrated (0.0054s) ==================
```

#### Postman
Screenshot 2023-11-04 at 3 49 22 PM

### CODE REVIEW

**Comment by santimintegui** [comment]
@juanarias93 estaria bueno meter en esta pr los cambios del FE asi no se rompe el foro, @Cocofredo te encargas vos de eso?

**Comment by Cocofredo** [comment]
Si! Una vez terminado todo completo que se pushee asi evitamos romper algo

**Comment by Cocofredo** [comment]
Por el lado de front quedo pronto!

**Comment by juanarias93** [comment]
> Por el lado de front quedo pronto!

@Cocofredo tremendo! 🙌 cuando aprueben acá ya lo mergeamos

**Review by santimintegui — APPROVED** [review]

**Pull request merged**
